spring:
  application:
    name: user-ms
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8091
  servlet:
    context-path: /api/adaptor

client:
  feign:
    base-url: http://localhost:3000