spring:
  application:
    name: user-ms
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8091
  servlet:
    context-path: /api/adaptor

client:
  feign:
    base-url: http://localhost:3000
    connection-timeout-millis: 20000
    read-timeout-millis: 5000
    retry:
      period-millis: 3000
      max-period-millis: 3000
      attempts: 1